name: e2e tests
on: workflow_dispatch
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            containers: [ 0, 1, 2, 3, 4 ]
    steps:
        # only install dependencies using
        # https://github.com/cypress-io/github-action
        - name: Test
          uses: cypress-io/github-action@v2
          with:
            spec: $(node cypress-partial.js 5 ${{ matrix.containers }})