name: e2e tests
on: workflow_dispatch
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            containers: [ 0, 1, 2, 3, 4 ]
    steps:
        - name: E2E
          run: cypress run --spec $(node cypress-partial.js 5 ${{ matrix.containers }})
