name: e2e tests
on: workflow_dispatch
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            containers: [1, 2, 3, 4]
    steps:
        - name: Install
          uses: actions/checkout@v2
        # only install dependencies using
        # https://github.com/cypress-io/github-action
        - name: Test
          uses: cypress-io/github-action@v2
          with:
            parallel: true
            record: false